### ISSUE TITLE
UI component and children props are missing after upgrading latest

### ISSUE THREAD

**Issue by vr-projects** [Jodacola/strontium#25]
We have initialized/created the new react project with 'react' and 'react-dom' version of 16.2.0 in which we are using 'react-strontium@0.2.8'. After upgrading it to latest version of react-strontium to 0.8.6 and **react** & **react-dom** to '18.2.0', the react-strontium package giving the 'children props are missing' error and there are some UI component that are not present in latest update/package like 'WaitSpinner',  'LoadMask', 'LoadIndicator'. Are some UI components are moved new package ? if yes then can we know the name of that package ?
And if it is in the upgraded version, in which version it has been provided ?

**Comment by Jodacola** [comment]
Hi! Very sorry for the delayed response here. Reviewing and will respond soon.

**Comment by Jodacola** [comment]
It's been several years since I worked on this project, but in the interest of separating concerns, I moved out the UI components to a separate project upon v0.5 of react-strontium: https://github.com/Jodacola/strontium-components. It is published on NPM here: https://www.npmjs.com/package/react-strontium-components.

React itself has changed quite a bit since the last time I worked on these projects, but I'm going to pull everything up to see if there are some simple changes to be made to support the latest version of React that might address your pain points.

**Comment by Jodacola** [comment]
I've just finished upgrading this library, as well as https://github.com/Jodacola/strontium-components and https://github.com/Jodacola/strontium-signalr, to the current version of React.

I updated code and test suites to ensure that tests are passing and any issues with the library code impacting tests were addressed, but fair warning: I haven't actually tried to test this in a real project, so I would encourage you to take a look and see how things go. I'm going to close this as I've addressed your reported issues, but please feel free to open another issue and I'll do my best to help you through things.

v0.9.0 of this library will be the version you'll want to try.
